language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
branches:
  only:
    - py3-port
install:
  - sudo apt-get update
  - sudo apt-get install python-dev python3-dev libapt-pkg-dev
  - pip install -e git+https://anonscm.debian.org/git/apt/python-apt.git@0.8.3ubuntu8#egg=python-apt
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ./install-aptoffline; fi
script:
  - make travis
after_success: coveralls
notifications:
  email:
    - apt-offline-devel@lists.alioth.debian.org
